### ISSUE TITLE
🐛 [BUG] - bora deployar  a page?

### ISSUE THREAD

**Issue by stokebreakup** [joaoeymard/secure-pass#10]
### Description

E ai equipe!

bora deployar a page?

### Reproduction URL

`https://www.alura.com.br/artigos/como-colocar-projeto-no-ar-com-github-pages`

### Reproduction steps
o site explica tudo e faria sentido se isso for utilizado para testar diferentes browsers e sistemas operacionais (verificar se o codigo funciona em diferentes/multiplos dispositivos)

### Screenshots

```bash
none
```

### Logs

```bash
none
```

### Browsers

Firefox, Chrome, Safari, Microsoft Edge, Opera

### OS

Windows, Linux, Mac

**Comment by joaoeymard** [comment]
Opa! Boa noite.

Já existe um processo de deploy automático.
