### ISSUE TITLE
🐛 [BUG] - adicionar repo no docker hub?

### ISSUE THREAD

**Issue by stokebreakup** [joaoeymard/secure-pass#6]
### Description
Por favor e por obséquio, adicione a imagem oficial do [secure-pass](https://github.com/joaoeymard/secure-pass) no docker hub

### Reproduction URL
https://docs.docker.com/docker-hub/quickstart/

### Reproduction steps
O link acima explica passo a passo como criar a conta no docker hub e criar uma imagem oficial por lá. A vantagem é que qualquer pessoa interessada nesse projeto pode fazer uma build automatizada sem precisar instalar o docker, apenas utilizando a imagem já na nuvem.

### Screenshots
Sem imagem

### Logs
Não há log.

### Browsers
Firefox, Chrome, Safari, Microsoft Edge, Opera

### OS
Windows, Linux, Mac

**Comment by joaoeymard** [comment]
Essa é uma boa sugestão, vou colocar isso no todo
