### ISSUE TITLE
🐛 [BUG] - traduzir o projeto em vários idiomas, línguas, dialetos?

### ISSUE THREAD

**Issue by stokebreakup** [joaoeymard/secure-pass#8]
### Description
pergunta técnica. seria viável traduzir esse projeto incrível em outros idiomas, línguas, dialetos? (ou seja, internacionalizar? de modo que  de forma independente do país, cultura, língua, nacionalidade?)

### Reproduction URL
https://github.com/ParthJadhav/Tkinter-Designer/tree/master/docs

### Reproduction steps
1. O projeto [Tkinter-Designer](https://github.com/ParthJadhav/Tkinter-Designer/tree/master/docs) possui vários arquivos README.md em vários idiomas. podemos seguir a orientação deste projeto para este projeto?
2. posso ajudar se quiser

### Screenshots
Não há screenshots, mas uma informação complementar é que existem ferramentas para automatizar isso:
- chat-gpt
- google tradutor
- weblate.org/crowdin.org (empresas que contratam tradutores ou por outra tradutores de todo mundo contribuem com código aberto, e nesse caso traduzem muitos projetos como linux, gimp e outros dentro/fora destas plataformas como crowdin/weblate e outros; há sempre soluções boas por aí)
- eu, você ou qualquer pessoa que conheça algum idioma, e queira traduzir

### Logs
nada.

### Browsers

Firefox, Chrome, Safari, Microsoft Edge, Opera

### OS

Windows, Linux, Mac

**Comment by joaoeymard** [comment]
A ideia é internacionalizar o README, ou a aplicação?
